version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:3000"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
